---
language: go

go:
  - tip
  - 1.5

go_import_path: chaos-galago

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
